### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by orochitian** [anseyuyin/AStar-Process#1]
你好！
   我正在学习A STAR算法。我遇到了一个问题，在你的demo中，我发现这个问题依然存在。如图：

![image](https://user-images.githubusercontent.com/28913785/69505747-6ee7fe80-0f66-11ea-9a28-c3d3e23dfa12.png)

   当代价相同的时候，无法保证最终答案是最佳路径。
   如果你很懂A STAR算法，我想知道，是否这个算法本身就存在这样的问题？
   如果只是我们自身问题，如何修正这个问题？
   非常期待您的回答！

**Comment by anseyuyin** [comment]
算法实现问题，已处理。
